PKG_NAME="tcpdump"
PKG_VERSION="4.99.6"
PKG_URL="https://www.tcpdump.org/release/tcpdump-4.99.6.tar.gz"
PKG_SRCDIR="tcpdump-4.99.6"

BUILD_TYPE="cmake"
CMAKE_ARGS=(
    "-DCMAKE_C_FLAGS=-I/opt/cygwin-port/include"
    "-DCMAKE_EXE_LINKER_FLAGS=-L/opt/cygwin-port/lib"
    "-DPCAP_ROOT=/opt/cygwin-port"
)
BUILD_TARGETS=""   # build all

INSTALL_BINS=("tcpdump")
INSTALL_DIR="/usr/local/bin"
