PKG_NAME="tshark"
PKG_VERSION="4.4.9"
PKG_URL="https://2.na.dl.wireshark.org/src/wireshark-4.4.9.tar.xz"
PKG_SRCDIR="wireshark-4.4.9"

BUILD_TYPE="cmake_ninja"
CMAKE_ARGS=(
    "-DBUILD_wireshark=OFF"
    "-DBUILD_logray=OFF"
    "-DENABLE_PCAP=ON"
    "-DPCAP_ROOT=/opt/cygwin-port"
    "-DCMAKE_C_FLAGS=-I/opt/cygwin-port/include"
    "-DCMAKE_EXE_LINKER_FLAGS=-L/opt/cygwin-port/lib"
    "-DPython3_EXECUTABLE=/usr/bin/python3"
)
BUILD_TARGETS="tshark dumpcap"

INSTALL_BINS=("tshark" "dumpcap")
INSTALL_DIR="/usr/local/bin"
